### ISSUE TITLE
Separate PM 2.5 and PM 10 readings

### ISSUE THREAD

**Issue by cpuks** [bieniu/ha-nettigo-air-monitor#2]
Any chance to get separate entities for PM 2.5 and PM 10 readings? I've got SDS011 / BME280 / HECA so I can help to provide necessary data.

**Comment by bieniu** [comment]
Sorry but no. This integration is already part of the official HA repository (will be available to users in HA 2021.6). Official integrations have to use `air_quality` platform for PM2.5, PM10 values. You can use a sensor template if you need a separate PM10 entity.
